import type { Metadata } from 'next';

import { RegisterForm } from '@/features/auth/components/organisms/register-form';

export const metadata: Metadata = {
  title: 'Register',
  description: 'Generated by create next app',
};

export default function RegisterPage() {
  return (
    <RegisterForm/>
  );
}
