import Heading from '@/shared/components/atoms/heading';
import Hero from '@/shared/components/atoms/hero';
import NewsLetter from '@/shared/components/atoms/newsletter';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      
    </>
  );
}
