import type { Metadata } from 'next';

import { LoginForm } from '@/features/auth/components/organisms/login-form';

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function LoginPage() {
  return (
    <LoginForm/>
  );
}
