import TemplateList from "@/features/templates/components/templates/TemplateList";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: 'Windflow - Templates',
    description: 'Generated by create next app',
  };
  
export default function Page() {
    return <TemplateList/>
}