import Pricing from "@/features/home/molecules/Pricing";
import { Metadata } from "next";
export const metadata: Metadata = {
   title: 'Windflow - Pricing',
   description: 'Generated by create next app',
 };
 
export default function Page() {
    return (
       <div className="mt-6">
          <Pricing/>
       </div>
    )
}