import About from '@/shared/components/molecules/about';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <About/>
    </>
  );
}
