import React from 'react';
import Contact from '@/shared/components/molecules/contact-us';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contact US',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      <Contact/>
    </>
  );
}
