import type { Metadata } from 'next';

import { RegisterForm } from '@/features/auth/components/organisms/register-form';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Register',
  description: 'Generated by create next app',
};

export default function LoginPage() {
  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl">Register</CardTitle>
          <CardDescription>Register your account</CardDescription>
        </CardHeader>
        <CardContent>
          <RegisterForm />
           <div className='flex items-center py-2 justify-center'>
            <Link href={'/login'}>Go back to Login</Link>
         </div>
        </CardContent>
      </Card>
    </div>
  );
}
